# Generated by Django 4.2.8 on 2025-06-11 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_attendance_time_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='time_in',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='time_out',
        ),
    ]
