# Generated by Django 4.2.8 on 2025-06-14 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_remove_userprofile_time_in_and_more'),
        ('crud', 'add_notes_to_attendance'),
    ]

    operations = [
    ]
