# Generated by Django 4.2.8 on 2025-06-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_merge_20250614_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='notes',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
